### PR TITLE
Update Nuget packages to latest version

### PR DESCRIPTION
**Pull request by atp-tha**
Updated Microsoft's packages and JSON.NET to latest stable version.

### CODE REVIEW

**Comment by TanukiSharp** [comment]
On the machine I'm testing here, I often get this error when trying to compile project that were originally made for .NET 1.x and now on .NET 2.x.

```
The current .NET SDK does not support targeting .NET Core 2.0.  Either target .NET Core 1.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.0.
```
In file `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets` at line 112.

I usually fix this by simply removing the `global.json` file.

This error may not be related to your pull request, but could you check if this is OK to remove the `global.json` file anyway, please ?

Thanks for your help.

**Comment by atp-tha** [comment]
Thanks for the info. I'll see what I can do.

**Comment by TanukiSharp** [comment]
Thanks, but basically you just have to delete the `global.json` file, restart Visual Studio if it was opened, and see if it still build. If it does, let me know and I will merge your PR, then make a commit to remove the `global.json` file.

**Comment by atp-tha** [comment]
I can confirm that it still builds after deleting the file. But I suggest you check these info out first before deciding if you want to delete the file or not.

Reference: [global.json overview](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json)

As stated by Microsoft, that file dictates .NET Core SDK versions which .NET Core CLI will use. If you want to define that later (e.g. to define it for a build script), you will have to run these command:
`dotnet new globaljson --sdk-version (version you want)`

**Comment by TanukiSharp** [comment]
Thanks for your work, and sorry for the extremely long delay.

**Pull request merged**
